### ISSUE TITLE
Add support for high-level rules

### ISSUE THREAD

**Issue by techpeace** [michaelherold/interactor-contracts#10]
First off, great job with this! It's exactly what I was looking for.

I was wondering if you had any plans on supporting [high-level rules](http://dry-rb.org/gems/dry-validation/high-level-rules/) in contracts. At first, I incorrectly assumed that this was already supported.

If you aren't already looking into that, I may give it a shot. Thanks!

**Comment by michaelherold** [comment]
Do high-level rules not already work? Since we're just delegating to a schema it seems like they should.

I'm not actively using `interactor` right now, so development on this is slow-going. I'd be perfectly happy to accept a PR for the functionality if you're up for it.

I'm trying out a new maintainership policy of making people co-maintainers sooner than later, so if you push a feature I'll offer co-maintainership to you.

Thanks for your interest!

**Comment by michaelherold** [comment]
dry-validation 1.0 has removed the concept of high-level rules. Even so, I think this is already incorporated so I'm going to go ahead and close it.
